<a href="https://colab.research.google.com/github/Olegman11/11/blob/main/F5_Pandas_in_Python_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#       importing the pandas library
import pandas as pd

In [8]:
# uploading data from the csv-file into the variable
new_data = pd.read_csv('/content/datafile2_jobs.csv', encoding='cp1251')

In [9]:
# to show my data
new_data

                          Job Role  Starting Salary  Vacancies
0                  Cloud Architect          Ј48,000    38000.0
1                 Python Developer          Ј42,000    42000.0
2    Cybersecurity Analyst/Manager          Ј38,000    13000.0
3   AI / Machine Learning Engineer          Ј52,000    27000.0
4              Technical Architect          Ј50,000    48000.0
5                  DevOps Engineer          Ј44,000    27000.0
6                   Data Scientist          Ј39,000    14000.0
7                Software Engineer          Ј35,000        NaN
8                  Product Manager          Ј40,000    18000.0
9                    Data Engineer          Ј36,000    37000.0
10            Full-Stack Developer          Ј34,000    11000.0
11                  UX/UI Designer          Ј30,000    23000.0
12       Digital Marketing Manager          Ј28,000    39000.0
13                Business Analyst          Ј33,000    24000.0
14           IT Support Technician          Ј25,000    37000.0

In [10]:
# the command 'head' shows the top rows of my data
new_data.head(5)

                         Job Role  Starting Salary  Vacancies
0                 Cloud Architect          Ј48,000    38000.0
1                Python Developer          Ј42,000    42000.0
2   Cybersecurity Analyst/Manager          Ј38,000    13000.0
3  AI / Machine Learning Engineer          Ј52,000    27000.0
4             Technical Architect          Ј50,000    48000.0

In [11]:
# the command 'tail' shows the bottom rows of my data
new_data.tail(5)

                     Job Role  Starting Salary  Vacancies
10       Full-Stack Developer          Ј34,000    11000.0
11             UX/UI Designer          Ј30,000    23000.0
12  Digital Marketing Manager          Ј28,000    39000.0
13           Business Analyst          Ј33,000    24000.0
14      IT Support Technician          Ј25,000    37000.0

In [12]:
# the command 'shape' shows the top of my data
new_data.shape

(15, 3)

In [13]:
# the command 'describe' shows statistic distribution of my data
new_data.describe()

          Vacancies
count     14.000000
mean   28428.571429
std    11862.768426
min    11000.000000
25%    19250.000000
50%    27000.000000
75%    37750.000000
max    48000.000000

In [14]:
# the command 'info' shows statistic distribution of my data
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job Role          15 non-null     object
 1    Starting Salary  15 non-null     object
 2   Vacancies         14 non-null     float64
dtypes: float64(1), object(2)
memory usage: 492.0+ bytes

In [15]:
# the command 'columns' shows columns names in my table
new_data.columns

Index(['Job Role', ' Starting Salary', 'Vacancies'], dtype='object')

In [16]:
# the command 'copy' does a copy of my data not to lose it
data = new_data.copy()
data

                          Job Role  Starting Salary  Vacancies
0                  Cloud Architect          Ј48,000    38000.0
1                 Python Developer          Ј42,000    42000.0
2    Cybersecurity Analyst/Manager          Ј38,000    13000.0
3   AI / Machine Learning Engineer          Ј52,000    27000.0
4              Technical Architect          Ј50,000    48000.0
5                  DevOps Engineer          Ј44,000    27000.0
6                   Data Scientist          Ј39,000    14000.0
7                Software Engineer          Ј35,000        NaN
8                  Product Manager          Ј40,000    18000.0
9                    Data Engineer          Ј36,000    37000.0
10            Full-Stack Developer          Ј34,000    11000.0
11                  UX/UI Designer          Ј30,000    23000.0
12       Digital Marketing Manager          Ј28,000    39000.0
13                Business Analyst          Ј33,000    24000.0
14           IT Support Technician          Ј25,000    37000.0

DATA CLEANING

In [17]:
# to have a look at my columns names
data.columns

Index(['Job Role', ' Starting Salary', 'Vacancies'], dtype='object')

In [18]:
# to put the column's names into variable
column_name = data.columns
cl_names = {'Job Role': 'Role',
            ' Starting Salary':'Salary',
            'Vacancies': 'Recent Vacancies'}
# changing columns names, 'inplace' means permanent changing, replacing names
data.rename(columns= cl_names, inplace=True) #inplace=True means permanently replaced

In [19]:
data

                              Role   Salary  Recent Vacancies
0                  Cloud Architect  Ј48,000           38000.0
1                 Python Developer  Ј42,000           42000.0
2    Cybersecurity Analyst/Manager  Ј38,000           13000.0
3   AI / Machine Learning Engineer  Ј52,000           27000.0
4              Technical Architect  Ј50,000           48000.0
5                  DevOps Engineer  Ј44,000           27000.0
6                   Data Scientist  Ј39,000           14000.0
7                Software Engineer  Ј35,000               NaN
8                  Product Manager  Ј40,000           18000.0
9                    Data Engineer  Ј36,000           37000.0
10            Full-Stack Developer  Ј34,000           11000.0
11                  UX/UI Designer  Ј30,000           23000.0
12       Digital Marketing Manager  Ј28,000           39000.0
13                Business Analyst  Ј33,000           24000.0
14           IT Support Technician  Ј25,000           37000.0

In [20]:
data = new_data.copy()
data

                          Job Role  Starting Salary  Vacancies
0                  Cloud Architect          Ј48,000    38000.0
1                 Python Developer          Ј42,000    42000.0
2    Cybersecurity Analyst/Manager          Ј38,000    13000.0
3   AI / Machine Learning Engineer          Ј52,000    27000.0
4              Technical Architect          Ј50,000    48000.0
5                  DevOps Engineer          Ј44,000    27000.0
6                   Data Scientist          Ј39,000    14000.0
7                Software Engineer          Ј35,000        NaN
8                  Product Manager          Ј40,000    18000.0
9                    Data Engineer          Ј36,000    37000.0
10            Full-Stack Developer          Ј34,000    11000.0
11                  UX/UI Designer          Ј30,000    23000.0
12       Digital Marketing Manager          Ј28,000    39000.0
13                Business Analyst          Ј33,000    24000.0
14           IT Support Technician          Ј25,000    37000.0

CHECK NULL DATA VALUES

```
# This is formatted as code
```

In [21]:
# CHECK NULL DATA VALUES in my data
data.isnull()

    Job Role   Starting Salary  Vacancies
0      False             False      False
1      False             False      False
2      False             False      False
3      False             False      False
4      False             False      False
5      False             False      False
6      False             False      False
7      False             False       True
8      False             False      False
9      False             False      False
10     False             False      False
11     False             False      False
12     False             False      False
13     False             False      False
14     False             False      False

In [31]:
# CHECK sum of NULL DATA VALUES in my data
data.isnull().sum()

Job Role            0
 Starting Salary    0
Vacancies           0
dtype: int64

In [23]:
# replacement of NULL DATA VALUES in my data
mean_val = data['Vacancies'].mean()    #mean_val - is a variable where I put 3st column Vacancies
print(mean_val)                        # and get a mean value (average) from the column

28428.571428571428

In [24]:
# formating the data
mean_val = data['Vacancies'].mean()
print(format(mean_val, " .2f"))      # and get a mean value (average) from the colum
data['Vacancies'].fillna             #

 28428.57

<bound method NDFrame.fillna of 0     38000.0
1     42000.0
2     13000.0
3     27000.0
4     48000.0
5     27000.0
6     14000.0
7         NaN
8     18000.0
9     37000.0
10    11000.0
11    23000.0
12    39000.0
13    24000.0
14    37000.0
Name: Vacancies, dtype: float64>

In [25]:
# formating the data
mean_val = data['Vacancies'].mean()
print(format(mean_val, " .2f"))      # and get a mean value (average) from the colum
data['Vacancies'].fillna             #

 28428.57

<bound method NDFrame.fillna of 0     38000.0
1     42000.0
2     13000.0
3     27000.0
4     48000.0
5     27000.0
6     14000.0
7         NaN
8     18000.0
9     37000.0
10    11000.0
11    23000.0
12    39000.0
13    24000.0
14    37000.0
Name: Vacancies, dtype: float64>

In [26]:
# formating the data
mean_val = data['Vacancies'].mean()
print(format(mean_val, " .2f"))      # and get a mean value (average) from the colum
data['Vacancies'].fillna            #

 28428.57

<bound method NDFrame.fillna of 0     38000.0
1     42000.0
2     13000.0
3     27000.0
4     48000.0
5     27000.0
6     14000.0
7         NaN
8     18000.0
9     37000.0
10    11000.0
11    23000.0
12    39000.0
13    24000.0
14    37000.0
Name: Vacancies, dtype: float64>

In [34]:
# formating the data
mean_val = data['Vacancies'].mean()
print(format(mean_val, " .2f"))      # # formating the data

 28428.57

In [35]:
# fill new data in missed cells with the function fillna()

data['Vacancies'].fillna(mean_val, inplace= True) #inplace=True means permanently replaced
# or i can do data['Vacancies'] = data['Vacancies'].fillna(mean_val)
# without 'inplace= True' in brackets

/tmp/ipykernel_11854/1369661055.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Vacancies'].fillna(mean_val, inplace= True) #inplace=True means permanently replaced

In [36]:
data['Vacancies'].fillna(mean_val, inplace= True)
data

/tmp/ipykernel_11854/3165384646.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Vacancies'].fillna(mean_val, inplace= True)

                          Job Role  Starting Salary     Vacancies
0                  Cloud Architect          Ј48,000  38000.000000
1                 Python Developer          Ј42,000  42000.000000
2    Cybersecurity Analyst/Manager          Ј38,000  13000.000000
3   AI / Machine Learning Engineer          Ј52,000  27000.000000
4              Technical Architect          Ј50,000  48000.000000
5                  DevOps Engineer          Ј44,000  27000.000000
6                   Data Scientist          Ј39,000  14000.000000
7                Software Engineer          Ј35,000  28428.571429
8                  Product Manager          Ј40,000  18000.000000
9                    Data Engineer          Ј36,000  37000.000000
10            Full-Stack Developer          Ј34,000  11000.000000
11                  UX/UI Designer          Ј30,000  23000.000000
12       Digital Marketing Manager          Ј28,000  39000.000000
13                Business Analyst          Ј33,000  24000.000000
14           IT Support Technician          Ј25,000  37000.000000