<a href="https://colab.research.google.com/github/Olegman11/11/blob/main/F6_Pandas_in_Python_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
# turning on pandas library
import pandas as pd

In [2]:
salesdata = pd.read_csv('/F6_sales_data_sample.csv') # uploading data in pandas
salesdata

,Order ID,Order Date,Year,GDSOrder Date,Sales Rep,City,State,Country,Region,Segment,Sales,Profit,item
0,BN-2013-7983986,11/30/2013,2013,11302013,Daniel Hamilton,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$261.84,$248.49,Fasteners
1,AZ-2014-4585623,02/01/2014,2014,212014,Emma Davis,Maidenhead,England,United Kingdom,North,Consumer,$899.81,$298.74,Paper
2,BN-2011-5133715,05/19/2011,2011,5192011,Mary Parker,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$161.54,$9.95,Supplies
3,AZ-2011-9474441,08/01/2011,2011,812011,Ruby Patel,Valence,Auvergne-Rhône-Alpes,France,Central,Home Office,$191.39,$217.58,Bookcases
4,BN-2013-1485133,03/13/2013,2013,3132013,Alice Smith,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$735.74,$182.89,Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,AZ-2014-9482400,02/16/2014,2014,2162014,Rebecca Chamberlain,Worcester,England,United Kingdom,North,Consumer,$97.77,$176.90,Envelopes
96,BN-2011-1500847,10/01/2011,2011,1012011,Rebecca Chamberlain,Southport,England,United Kingdom,North,Consumer,$215.61,$95.87,Art
97,BN-2014-3903399,04/29/2014,2014,4292014,Claire Brown,Southport,England,United Kingdom,North,Corporate,$936.55,($8.60),Supplies
98,AZ-2014-3724067,09/01/2014,2014,912014,Jose Gambino,Stockholm,Stockholm,Sweden,North,Home Office,$87.26,$144.55,Phones
99,AZ-2014-4514136,01/21/2014,2014,1212014,Mary Parker,Echirolles,Auvergne-Rhône-Alpes,France,Central,Home Office,$496.13,$244.00,Chairs

In [11]:
# copy data in case
sdata = salesdata.copy()
salesdata

,Order ID,Order Date,Year,GDSOrder Date,Sales Rep,City,State,Country,Region,Segment,Sales,Profit,item
0,BN-2013-7983986,11/30/2013,2013,11302013,Daniel Hamilton,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$261.84,$248.49,Fasteners
1,AZ-2014-4585623,02/01/2014,2014,212014,Emma Davis,Maidenhead,England,United Kingdom,North,Consumer,$899.81,$298.74,Paper
2,BN-2011-5133715,05/19/2011,2011,5192011,Mary Parker,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$161.54,$9.95,Supplies
3,AZ-2011-9474441,08/01/2011,2011,812011,Ruby Patel,Valence,Auvergne-Rhône-Alpes,France,Central,Home Office,$191.39,$217.58,Bookcases
4,BN-2013-1485133,03/13/2013,2013,3132013,Alice Smith,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$735.74,$182.89,Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,AZ-2014-9482400,02/16/2014,2014,2162014,Rebecca Chamberlain,Worcester,England,United Kingdom,North,Consumer,$97.77,$176.90,Envelopes
96,BN-2011-1500847,10/01/2011,2011,1012011,Rebecca Chamberlain,Southport,England,United Kingdom,North,Consumer,$215.61,$95.87,Art
97,BN-2014-3903399,04/29/2014,2014,4292014,Claire Brown,Southport,England,United Kingdom,North,Corporate,$936.55,($8.60),Supplies
98,AZ-2014-3724067,09/01/2014,2014,912014,Jose Gambino,Stockholm,Stockholm,Sweden,North,Home Office,$87.26,$144.55,Phones
99,AZ-2014-4514136,01/21/2014,2014,1212014,Mary Parker,Echirolles,Auvergne-Rhône-Alpes,France,Central,Home Office,$496.13,$244.00,Chairs

Dropping non necessarily columns (deleting)

In [12]:
# dropping columns
sdata.drop(columns = 'GDSOrder Date', inplace = True)

In [14]:
# checking if it was deleted
sdata

,Order ID,Order Date,Year,Sales Rep,City,State,Country,Region,Segment,Sales,Profit,item
0,BN-2013-7983986,11/30/2013,2013,Daniel Hamilton,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$261.84,$248.49,Fasteners
1,AZ-2014-4585623,02/01/2014,2014,Emma Davis,Maidenhead,England,United Kingdom,North,Consumer,$899.81,$298.74,Paper
2,BN-2011-5133715,05/19/2011,2011,Mary Parker,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$161.54,$9.95,Supplies
3,AZ-2011-9474441,08/01/2011,2011,Ruby Patel,Valence,Auvergne-Rhône-Alpes,France,Central,Home Office,$191.39,$217.58,Bookcases
4,BN-2013-1485133,03/13/2013,2013,Alice Smith,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$735.74,$182.89,Paper
...,...,...,...,...,...,...,...,...,...,...,...,...
95,AZ-2014-9482400,02/16/2014,2014,Rebecca Chamberlain,Worcester,England,United Kingdom,North,Consumer,$97.77,$176.90,Envelopes
96,BN-2011-1500847,10/01/2011,2011,Rebecca Chamberlain,Southport,England,United Kingdom,North,Consumer,$215.61,$95.87,Art
97,BN-2014-3903399,04/29/2014,2014,Claire Brown,Southport,England,United Kingdom,North,Corporate,$936.55,($8.60),Supplies
98,AZ-2014-3724067,09/01/2014,2014,Jose Gambino,Stockholm,Stockholm,Sweden,North,Home Office,$87.26,$144.55,Phones
99,AZ-2014-4514136,01/21/2014,2014,Mary Parker,Echirolles,Auvergne-Rhône-Alpes,France,Central,Home Office,$496.13,$244.00,Chairs

In [15]:
# checking for missing values in the data
sdata.isnull().sum()

Order ID      0
Order Date    0
Year          0
Sales Rep     0
City          0
State         0
Country       0
Region        0
Segment       0
Sales         0
Profit        0
item          0
dtype: int64

In [16]:
# checking for missing values in the exact column
sdata['Order Date'].isnull().sum()

np.int64(0)

In [17]:
# Another way to check for missing values in the exact column
sdata.Region.isnull().sum()

np.int64(0)

In [18]:
# check for unique values in columns
sdata.Country.unique()

array(['Germany', 'United Kingdom', 'France', 'Sweden', 'Netherlands'],
      dtype=object)

In [19]:
# check for unique values in columns
sdata.Region.unique()

array(['Central', 'North'], dtype=object)

In [20]:
# replacing values
sdata.Country = sdata.Country.replace(['Netherlands'], 'Ukraine')

In [21]:
sdata.Country.unique()

array(['Germany', 'United Kingdom', 'France', 'Sweden', 'Ukraine'],
      dtype=object)

In [26]:
# count lenght of Items
number_countries = len(sdata.Country.unique())
print(number_countries)

5

In [49]:
# selecting data from the dataframe
sdata_items = sdata[['Sales Rep', 'City', 'State','Country']]

In [50]:
sdata_items

              Sales Rep        City                   State         Country
0       Daniel Hamilton   Bielefeld  North Rhine-Westphalia         Germany
1            Emma Davis  Maidenhead                 England  United Kingdom
2           Mary Parker   Bielefeld  North Rhine-Westphalia         Germany
3            Ruby Patel     Valence    Auvergne-Rhône-Alpes          France
4           Alice Smith   Bielefeld  North Rhine-Westphalia         Germany
..                  ...         ...                     ...             ...
95  Rebecca Chamberlain   Worcester                 England  United Kingdom
96  Rebecca Chamberlain   Southport                 England  United Kingdom
97         Claire Brown   Southport                 England  United Kingdom
98         Jose Gambino   Stockholm               Stockholm          Sweden
99          Mary Parker  Echirolles    Auvergne-Rhône-Alpes          France

[100 rows x 4 columns]

In [55]:
# selecting data from the dataframe
sdata_items1 = sdata[['Order ID', 'Sales', 'item']]
sdata_items1

           Order ID    Sales       item
0   BN-2013-7983986  $261.84  Fasteners
1   AZ-2014-4585623  $899.81      Paper
2   BN-2011-5133715  $161.54   Supplies
3   AZ-2011-9474441  $191.39  Bookcases
4   BN-2013-1485133  $735.74      Paper
..              ...      ...        ...
95  AZ-2014-9482400   $97.77  Envelopes
96  BN-2011-1500847  $215.61        Art
97  BN-2014-3903399  $936.55   Supplies
98  AZ-2014-3724067   $87.26     Phones
99  AZ-2014-4514136  $496.13     Chairs

[100 rows x 3 columns]

In [65]:
# replacing data in the first rows in dataset
sdata_items1.loc[0] = {'Order ID': 'Item0000', 'Sales': 35, 'item': 'Cucumber'}
sdata_items1

           Order ID    Sales       item
0          Item0000       35   Cucumber
1          Item0001      NaN        NaN
2   BN-2011-5133715  $161.54   Supplies
3   AZ-2011-9474441  $191.39  Bookcases
4   BN-2013-1485133  $735.74      Paper
..              ...      ...        ...
95  AZ-2014-9482400   $97.77  Envelopes
96  BN-2011-1500847  $215.61        Art
97  BN-2014-3903399  $936.55   Supplies
98  AZ-2014-3724067   $87.26     Phones
99  AZ-2014-4514136  $496.13     Chairs

[100 rows x 3 columns]

In [64]:
# replacing data in the first rows in dataset
sdata_items1.loc[1] = {'Order ID': 'Item0001'}
sdata_items1

           Order ID    Sales       item
0          Item0000       35   Cucumber
1          Item0001      NaN        NaN
2   BN-2011-5133715  $161.54   Supplies
3   AZ-2011-9474441  $191.39  Bookcases
4   BN-2013-1485133  $735.74      Paper
..              ...      ...        ...
95  AZ-2014-9482400   $97.77  Envelopes
96  BN-2011-1500847  $215.61        Art
97  BN-2014-3903399  $936.55   Supplies
98  AZ-2014-3724067   $87.26     Phones
99  AZ-2014-4514136  $496.13     Chairs

[100 rows x 3 columns]

In [68]:
# looking for rows where item = Paper
sdata_items1.loc[sdata_items1['item'] == 'Paper']

           Order ID    Sales   item
4   BN-2013-1485133  $735.74  Paper
12  AZ-2011-2186736  $368.88  Paper
21  BN-2011-9119811  $969.28  Paper
34  BN-2012-8243184  $708.19  Paper
36  BN-2014-9220715  $263.85  Paper
47  BN-2013-5748343  $266.95  Paper
57  AZ-2013-9865254  $427.08  Paper
63  AZ-2011-8941247  $673.80  Paper
75  BN-2011-3231176  $376.82  Paper
83  BN-2013-4075308  $587.51  Paper

In [69]:
sdata_items1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order ID  100 non-null    object
 1   Sales     99 non-null     object
 2   item      99 non-null     object
dtypes: object(3)
memory usage: 2.5+ KB

In [76]:
salesdata3 = pd.read_csv('/content/datafile2_jobs.csv', encoding='cp1251') # uploading data in pandas
salesdata3

                          Job Role  Starting Salary  Vacancies
0                  Cloud Architect          Ј48,000    38000.0
1                 Python Developer          Ј42,000    42000.0
2    Cybersecurity Analyst/Manager          Ј38,000    13000.0
3   AI / Machine Learning Engineer          Ј52,000    27000.0
4              Technical Architect          Ј50,000    48000.0
5                  DevOps Engineer          Ј44,000    27000.0
6                   Data Scientist          Ј39,000    14000.0
7                Software Engineer          Ј35,000        NaN
8                  Product Manager          Ј40,000    18000.0
9                    Data Engineer          Ј36,000    37000.0
10            Full-Stack Developer          Ј34,000    11000.0
11                  UX/UI Designer          Ј30,000    23000.0
12       Digital Marketing Manager          Ј28,000    39000.0
13                Business Analyst          Ј33,000    24000.0
14           IT Support Technician          Ј25,000    37000.0

In [77]:
# looking for rows where Vacancies >= 25000
salesdata3.loc[salesdata3['Vacancies'] >= 25000]

                          Job Role  Starting Salary  Vacancies
0                  Cloud Architect          Ј48,000    38000.0
1                 Python Developer          Ј42,000    42000.0
3   AI / Machine Learning Engineer          Ј52,000    27000.0
4              Technical Architect          Ј50,000    48000.0
5                  DevOps Engineer          Ј44,000    27000.0
9                    Data Engineer          Ј36,000    37000.0
12       Digital Marketing Manager          Ј28,000    39000.0
14           IT Support Technician          Ј25,000    37000.0

In [80]:
# total sum of the Vacancies column
Total_salary = salesdata3['Vacancies'].sum()
print(Total_salary)

398000.0

In [81]:
# Maximum value of the Vacancies column
Max_salary = salesdata3['Vacancies'].max()
print(Max_salary)

48000.0

In [82]:
# Unique value of the Vacancies column
salesdata3['Vacancies'].unique()

array([38000., 42000., 13000., 27000., 48000., 14000.,    nan, 18000.,
       37000., 11000., 23000., 39000., 24000.])

In [86]:
# searching value in the column 'Vacancies' beetween 25 000 and 30 000
salesdata3[(salesdata3['Vacancies'] >= 25000) & (salesdata3['Vacancies'] <= 30000)]

                         Job Role  Starting Salary  Vacancies
3  AI / Machine Learning Engineer          Ј52,000    27000.0
5                 DevOps Engineer          Ј44,000    27000.0

In [89]:
salesdata3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job Role          15 non-null     object
 1    Starting Salary  15 non-null     object
 2   Vacancies         14 non-null     float64
dtypes: float64(1), object(2)
memory usage: 492.0+ bytes

In [93]:
salesdata = pd.read_csv('/content/F6_sales_data_sample.csv') # uploading data in pandas
salesdata

,Order ID,Order Date,Year,GDSOrder Date,Sales Rep,City,State,Country,Region,Segment,Sales,Profit,item
0,BN-2013-7983986,11/30/2013,2013,11302013,Daniel Hamilton,Bielefeld,North Rhine-Westphalia,Germany,Central,Consumer,$261.84,$248.49,Fasteners
1,AZ-2014-4585623,02/01/2014,2014,212014,Emma Davis,Maidenhead,England,United Kingdom,North,Consumer,$899.81,$298.74,Paper
2,BN-2011-5133715,05/19/2011,2011,5192011,Mary Parker,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$161.54,$9.95,Supplies
3,AZ-2011-9474441,08/01/2011,2011,812011,Ruby Patel,Valence,Auvergne-Rhône-Alpes,France,Central,Home Office,$191.39,$217.58,Bookcases
4,BN-2013-1485133,03/13/2013,2013,3132013,Alice Smith,Bielefeld,North Rhine-Westphalia,Germany,Central,Corporate,$735.74,$182.89,Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,AZ-2014-9482400,02/16/2014,2014,2162014,Rebecca Chamberlain,Worcester,England,United Kingdom,North,Consumer,$97.77,$176.90,Envelopes
96,BN-2011-1500847,10/01/2011,2011,1012011,Rebecca Chamberlain,Southport,England,United Kingdom,North,Consumer,$215.61,$95.87,Art
97,BN-2014-3903399,04/29/2014,2014,4292014,Claire Brown,Southport,England,United Kingdom,North,Corporate,$936.55,($8.60),Supplies
98,AZ-2014-3724067,09/01/2014,2014,912014,Jose Gambino,Stockholm,Stockholm,Sweden,North,Home Office,$87.26,$144.55,Phones
99,AZ-2014-4514136,01/21/2014,2014,1212014,Mary Parker,Echirolles,Auvergne-Rhône-Alpes,France,Central,Home Office,$496.13,$244.00,Chairs